"""Add messages model

Revision ID: 3800bb8fddb5
Revises: fca2f16a4a8a
Create Date: 2024-08-12 12:52:46.839019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3800bb8fddb5'
down_revision: Union[str, None] = 'fca2f16a4a8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
